### ISSUE TITLE
yaml content should not be inlined in python source files

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/commons#201]
In many places, we have inlined yaml content directly in python source files like this:

```
logging_file = """version: 1                                                                                               
disable_existing_loggers: False                                                                                            
formatters:                                                                                                                
    simple:                                                                                                                
        format: "%(asctime)s - %(pathname)s - %(filename)s:%(lineno)s - %(funcName)20s() - %(levelname)s - %(message)s" 
        datefmt: "%Y-%m-%dT%H:%M:%S%z"                                                                                     
                                                                                                                           
handlers:                                                                                                                  
    console:                                                                                                               
        class: logging.StreamHandler                                                                                       
        level: DEBUG                                                                                                       
        formatter: simple                                                                                                  
        stream: ext://sys.stdout 
```

This approach has multiple problems:

* yaml content is burried inside code and can be easily missed
* we can't easily check yaml syntax (eg. via yamllint) for all yaml content we have in repository during Travis CI check
* we can't work with those yaml files with other tools directly if needed
* people editing such bundled yaml files don't see yaml syntax highlighting

Instead of this, we should store yaml content in dedicated files directly and packaging them properly.
