### ISSUE TITLE
Attributes of Tendrl objects should be watchable

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/commons#837]
- Add "watch_attrs" (type: list) to Tendrl definition schema for the Object
   - eg: 
```
objects: 
    Cluster:
      enabled: True
      help: "Represents a cluster"
      list: /clusters
      value: clusters/$TendrlContext.integration_id
      watch_attrs: 
              - errors
              - status
```

- In Services (tendrl-node-agent, tendrl-gluster-integration etc) that can .save() an object, a watcher thread will be created per attribute of that instance of the object.

eg: /clusters/asdadwwasd/status  (creates 1 watcher per service for given integration_id/status)
