### ISSUE TITLE
Add support for storing more complex validations in definitions

### ISSUE THREAD

**Issue by shirshendu** [Tendrl/commons#870]
Currently in https://github.com/Tendrl/commons/blob/43d544d543cc3b0b82809789fb161cb113e6cb83/tendrl/commons/objects/definition/master.yaml#L268 : 
an attribute would have a `help` and a `type`.

```yaml
        volume_profiling_flag:
          help: Whether to enable/disable/leave as-is volume profiling
          type: String
```
Let us start adding support for more complex validations, possibly under a `validations` key.
For example, in the above example, we should have the `volume_profiling_flag` attribute as a String, as well as one-of-n values.

How about something like this:

```yaml
        volume_profiling_flag:
          help: Whether to enable/disable/leave as-is volume profiling
          type: String
          validations:
            type: String
            inclusion:
              - enable
              - disable
              - 'leave-as-is'            
```

It is up for discussion if we want to repeat the `type: String` in the validation as well. I would suggest being explicit, because we may have an attribute that needs to be casted if present, but not validated.
